# hash-identificacao: 6e9b7036a2cdb30fa6d365eccc7123ad6aebb3d3535c7c7e601e8d4d51851f93

# Configurações padrão disponíveis: https://docs.spring.io/spring-boot/appendix/application-properties/index.html

spring.application.name=projetofinalmedicos

# --- Servidor Web ---
# server.port=8080
# server.servlet.context-path=/  # Opcional: definir um contexto base para a API

# --- Jackson (serialização JSON formatada) ---
spring.jackson.serialization.INDENT_OUTPUT=true

# ATENÇÃO: As configurações de banco de dados e JPA abaixo NÃO são adicionadas pelo
# Spring Initializr oficial. Foram incluídas apenas para fins didáticos.

# --- Datasource (h2) ---
spring.datasource.url=jdbc:h2:mem:projetofinalmedicos
# Trocar a linha acima pelas duas linhas abaixo se H2 usar arquivos
# No Windows, o arquivo será criado no diretório C:\Users\<NOME_USUARIO>\projetofinalmedicos-h2-data.mv
# spring.datasource.url=jdbc:h2:file:~/projetofinalmedicos-h2-data
# spring.sql.init.platform=h2

spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- JPA / Hibernate ---
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# ATENÇÃO: PARA PROJETOS REAIS, RECOMENDA-SE DESCOMENTAR A OPÇÃO ABAIXO:
spring.jpa.open-in-view=false
